---
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - git
  - pytorch::pytorch>=2.0.0
  - pytorch::pytorch-cuda=12.4
  - nvidia::cuda-toolkit=12.4
  - conda-forge::numpy>=1.26.4
  - conda-forge::pandas>=2.0
  - conda-forge::tifffile>=2023.0
  - conda-forge::scipy>=1.11
  - conda-forge::h5py>=3.9
  - conda-forge::shapely>=2.0
  - conda-forge::rasterio>=1.3
  - pip
  - pip:
      - xformers>=0.0.18
      - huggingface_hub>=0.28.1
      - kronos@git+https://github.com/mahmoodlab/KRONOS.git
