# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - python =3.10.0
  - tifffile
  - typer
  - xarray
  - rasterio
  - scikit-image
  - geopandas
  - git
  - gcc
  - pip
  - pip:
      - tensorflow-cpu>=2.8,<2.9
      - deepcell>=0.12,<0.13
      - git+https://github.com/WEHI-SODA-Hub/MibiSegmentation.git
