bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - docs/README.md
  multiqc_config: false
  nextflow_config: false
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: WEHI SODA Hub
  description: Cell segmentation and downstream analysis pipeline for the multiplexed
    ion bream imaging (MIBI) spatial platform
  force: true
  is_nfcore: true
  name: spatialmibi
  org: nf-core
  outdir: spatialmibi
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.0.0dev
update: null
