---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - tifffile =2025.6.11
  - pandas =2.3.0
  - typer =0.16.0
